// Copyright (C) 2018 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Note that if you add/remove methods in this file you must update
// the metrics sql as well ./android/scripts/gen-grpc-sql.py
//
// Please group deleted methods in a block including the date (MM/DD/YY)
// it was removed. This enables us to easily keep metrics around after removal
//
// List of deleted methods
// rpc iWasDeleted (03/12/12)
// ...

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: emulator_controller.proto

package emulatorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmulatorController_StreamSensor_FullMethodName                  = "/android.emulation.control.EmulatorController/streamSensor"
	EmulatorController_GetSensor_FullMethodName                     = "/android.emulation.control.EmulatorController/getSensor"
	EmulatorController_SetSensor_FullMethodName                     = "/android.emulation.control.EmulatorController/setSensor"
	EmulatorController_SetPhysicalModel_FullMethodName              = "/android.emulation.control.EmulatorController/setPhysicalModel"
	EmulatorController_GetPhysicalModel_FullMethodName              = "/android.emulation.control.EmulatorController/getPhysicalModel"
	EmulatorController_StreamPhysicalModel_FullMethodName           = "/android.emulation.control.EmulatorController/streamPhysicalModel"
	EmulatorController_SetClipboard_FullMethodName                  = "/android.emulation.control.EmulatorController/setClipboard"
	EmulatorController_GetClipboard_FullMethodName                  = "/android.emulation.control.EmulatorController/getClipboard"
	EmulatorController_StreamClipboard_FullMethodName               = "/android.emulation.control.EmulatorController/streamClipboard"
	EmulatorController_SetBattery_FullMethodName                    = "/android.emulation.control.EmulatorController/setBattery"
	EmulatorController_GetBattery_FullMethodName                    = "/android.emulation.control.EmulatorController/getBattery"
	EmulatorController_SetGps_FullMethodName                        = "/android.emulation.control.EmulatorController/setGps"
	EmulatorController_GetGps_FullMethodName                        = "/android.emulation.control.EmulatorController/getGps"
	EmulatorController_SendFingerprint_FullMethodName               = "/android.emulation.control.EmulatorController/sendFingerprint"
	EmulatorController_SendKey_FullMethodName                       = "/android.emulation.control.EmulatorController/sendKey"
	EmulatorController_SendTouch_FullMethodName                     = "/android.emulation.control.EmulatorController/sendTouch"
	EmulatorController_SendMouse_FullMethodName                     = "/android.emulation.control.EmulatorController/sendMouse"
	EmulatorController_InjectWheel_FullMethodName                   = "/android.emulation.control.EmulatorController/injectWheel"
	EmulatorController_StreamInputEvent_FullMethodName              = "/android.emulation.control.EmulatorController/streamInputEvent"
	EmulatorController_SendPhone_FullMethodName                     = "/android.emulation.control.EmulatorController/sendPhone"
	EmulatorController_SendSms_FullMethodName                       = "/android.emulation.control.EmulatorController/sendSms"
	EmulatorController_SetPhoneNumber_FullMethodName                = "/android.emulation.control.EmulatorController/setPhoneNumber"
	EmulatorController_GetStatus_FullMethodName                     = "/android.emulation.control.EmulatorController/getStatus"
	EmulatorController_GetScreenshot_FullMethodName                 = "/android.emulation.control.EmulatorController/getScreenshot"
	EmulatorController_StreamScreenshot_FullMethodName              = "/android.emulation.control.EmulatorController/streamScreenshot"
	EmulatorController_StreamAudio_FullMethodName                   = "/android.emulation.control.EmulatorController/streamAudio"
	EmulatorController_InjectAudio_FullMethodName                   = "/android.emulation.control.EmulatorController/injectAudio"
	EmulatorController_GetLogcat_FullMethodName                     = "/android.emulation.control.EmulatorController/getLogcat"
	EmulatorController_StreamLogcat_FullMethodName                  = "/android.emulation.control.EmulatorController/streamLogcat"
	EmulatorController_SetVmState_FullMethodName                    = "/android.emulation.control.EmulatorController/setVmState"
	EmulatorController_GetVmState_FullMethodName                    = "/android.emulation.control.EmulatorController/getVmState"
	EmulatorController_SetDisplayConfigurations_FullMethodName      = "/android.emulation.control.EmulatorController/setDisplayConfigurations"
	EmulatorController_GetDisplayConfigurations_FullMethodName      = "/android.emulation.control.EmulatorController/getDisplayConfigurations"
	EmulatorController_StreamNotification_FullMethodName            = "/android.emulation.control.EmulatorController/streamNotification"
	EmulatorController_RotateVirtualSceneCamera_FullMethodName      = "/android.emulation.control.EmulatorController/rotateVirtualSceneCamera"
	EmulatorController_SetVirtualSceneCameraVelocity_FullMethodName = "/android.emulation.control.EmulatorController/setVirtualSceneCameraVelocity"
	EmulatorController_SetPosture_FullMethodName                    = "/android.emulation.control.EmulatorController/setPosture"
	EmulatorController_GetBrightness_FullMethodName                 = "/android.emulation.control.EmulatorController/getBrightness"
	EmulatorController_SetBrightness_FullMethodName                 = "/android.emulation.control.EmulatorController/setBrightness"
	EmulatorController_GetDisplayMode_FullMethodName                = "/android.emulation.control.EmulatorController/getDisplayMode"
	EmulatorController_SetDisplayMode_FullMethodName                = "/android.emulation.control.EmulatorController/setDisplayMode"
	EmulatorController_SetXrOptions_FullMethodName                  = "/android.emulation.control.EmulatorController/setXrOptions"
	EmulatorController_GetXrOptions_FullMethodName                  = "/android.emulation.control.EmulatorController/getXrOptions"
)

// EmulatorControllerClient is the client API for EmulatorController service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// An EmulatorController service lets you control the emulator.
// Note that this is currently an experimental feature, and that the
// service definition might change without notice. Use at your own risk!
//
// We use the following rough conventions:
//
// streamXXX --> streams values XXX (usually for emulator lifetime). Values
//
//	are updated as soon as they become available.
//
// getXXX    --> gets a single value XXX
// setXXX    --> sets a single value XXX, does not returning state, these
//
//	usually have an observable lasting side effect.
//
// sendXXX   --> send a single event XXX, possibly returning state information.
//
//	android usually responds to these events.
type EmulatorControllerClient interface {
	// set/get/stream the sensor data
	StreamSensor(ctx context.Context, in *SensorValue, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SensorValue], error)
	GetSensor(ctx context.Context, in *SensorValue, opts ...grpc.CallOption) (*SensorValue, error)
	SetSensor(ctx context.Context, in *SensorValue, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// set/get/stream the physical model, this is likely the one you are
	// looking for when you wish to modify the device state.
	SetPhysicalModel(ctx context.Context, in *PhysicalModelValue, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetPhysicalModel(ctx context.Context, in *PhysicalModelValue, opts ...grpc.CallOption) (*PhysicalModelValue, error)
	StreamPhysicalModel(ctx context.Context, in *PhysicalModelValue, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PhysicalModelValue], error)
	// Atomically set/get the current primary clipboard data.
	// Note that a call to setClipboard will result in an immediate
	// event for those who made a call to streamClipboard and are
	// on a different channel than the one used to set the clipboard.
	SetClipboard(ctx context.Context, in *ClipData, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetClipboard(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClipData, error)
	// Streams the current data on the clipboard. This will immediately produce
	// a result with the current state of the clipboard after which the stream
	// will block and wait until a new clip event is available from the guest.
	// Calling the setClipboard method above will not result in generating a
	// clip event. It is possible to lose clipboard events if the clipboard
	// updates very rapidly.
	StreamClipboard(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClipData], error)
	// Set/get the battery to the given state.
	SetBattery(ctx context.Context, in *BatteryState, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetBattery(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BatteryState, error)
	// Set the state of the gps.
	// Note: Setting the gps position will not be reflected in the user
	// interface. Keep in mind that android usually only samples the gps at 1
	// hz.
	SetGps(ctx context.Context, in *GpsState, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Gets the latest gps state as delivered by the setGps call, or location ui
	// if active.
	//
	// Note: this is not necessarily the actual gps coordinate visible at the
	// time, due to gps sample frequency (usually 1hz).
	GetGps(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GpsState, error)
	// Simulate a touch event on the finger print sensor.
	SendFingerprint(ctx context.Context, in *Fingerprint, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Send a keyboard event. Translating the event.
	SendKey(ctx context.Context, in *KeyboardEvent, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Send touch/mouse events. Note that mouse events can be simulated
	// by touch events.
	SendTouch(ctx context.Context, in *TouchEvent, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendMouse(ctx context.Context, in *MouseEvent, opts ...grpc.CallOption) (*emptypb.Empty, error)
	InjectWheel(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WheelEvent, emptypb.Empty], error)
	// Stream a series of input events to the emulator, the events will
	// arrive in order.
	StreamInputEvent(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InputEvent, emptypb.Empty], error)
	// Make a phone call.
	SendPhone(ctx context.Context, in *PhoneCall, opts ...grpc.CallOption) (*PhoneResponse, error)
	// Sends an sms message to the emulator.
	SendSms(ctx context.Context, in *SmsMessage, opts ...grpc.CallOption) (*PhoneResponse, error)
	// Sends an sms message to the emulator.
	SetPhoneNumber(ctx context.Context, in *PhoneNumber, opts ...grpc.CallOption) (*PhoneResponse, error)
	// Retrieve the status of the emulator. This will contain general
	// hardware information, and whether the device has booted or not.
	GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*EmulatorStatus, error)
	// Gets an individual screenshot in the desired format.
	//
	// The image will be scaled to the desired ImageFormat, while maintaining
	// the aspect ratio. The returned image will never exceed resolution of the
	// device display. Not setting the width or height (i.e. they are 0) will
	// result in using the display width and height.
	//
	// The resulting image will be properly oriented and can be displayed
	// directly without post processing. For example, if the device has a
	// 1080x1920 screen and is in landscape mode and called with no width or
	// height parameter, it will return a 1920x1080 image.
	//
	// The dimensions of the returned image will never exceed the corresponding
	// display dimensions. For example, this method will return a 1920x1080
	// screenshot, if the display resolution is 1080x1920 and a screenshot of
	// 2048x2048 is requested when the device is in landscape mode.
	//
	// This method will return an empty image if the display is not visible.
	GetScreenshot(ctx context.Context, in *ImageFormat, opts ...grpc.CallOption) (*Image, error)
	// Streams a series of screenshots in the desired format.
	//
	// A new frame will be delivered whenever the device produces a new frame.
	// Beware that this can produce a significant amount of data and that
	// certain translations can be very costly. For example, streaming a series
	// of png images is very cpu intensive.
	//
	// Images are produced according to the getScreenshot API described above.
	//
	// If the display is inactive, or becomes inactive, an empty image will be
	// delivered. Images will be delived again if the display becomes active and
	// new frames are produced.
	StreamScreenshot(ctx context.Context, in *ImageFormat, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Image], error)
	// Streams a series of audio packets in the desired format.
	// A new frame will be delivered whenever the emulated device
	// produces a new audio frame. You can expect packets to be
	// delivered in intervals of 20-30ms.
	//
	// Be aware that this can block when the emulator does not
	// produce any audio whatsoever!
	StreamAudio(ctx context.Context, in *AudioFormat, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioPacket], error)
	// Injects a series of audio packets to the android microphone.
	// A new frame will be delivered whenever the emulated device
	// requests a new audio frame. Audio is usually delivered at a rate
	// that the emulator is requesting frames. Audio will be stored in a
	// temporary buffer that can hold 300ms of audio.
	//
	// Notes:
	//   - Only the first audio format packet that is delivered will be
	//
	// honored. There is no need to send the audio format multiple times.
	//   - Real time audio currently immediately overrides the buffer. This
	//
	// means you must provide a constant rate of audio packets. The real
	// time mode is experimental. Timestamps of audio packets might be
	// used in the future to improve synchronization.
	//
	// -  INVALID_ARGUMENT (code 3) The sampling rate was too high/low
	// -  INVALID_ARGUMENT (code 3) The audio packet was too large to handle.
	// -  FAILED_PRECONDITION (code 9) If there was a microphone registered
	// already.
	InjectAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AudioPacket, emptypb.Empty], error)
	// Deprecated: Do not use.
	// Deprecated, please use the streamLogcat method instead.
	GetLogcat(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (*LogMessage, error)
	// Streams the logcat output from the emulator.
	// Note that parsed logcat messages are only available after L (Api >23)
	StreamLogcat(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogMessage], error)
	// Transition the virtual machine to the desired state. Note that
	// some states are only observable. For example you cannot transition
	// to the error state.
	SetVmState(ctx context.Context, in *VmRunState, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Gets the state of the virtual machine.
	GetVmState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VmRunState, error)
	// Atomically changes the current multi-display configuration.
	// After this call the given display configurations will be activated. You
	// can only update secondary displays. Displays with id 0 will be ignored.
	//
	// This call can result in the removal or addition of secondary displays,
	// the final display state can be observed by the returned configuration.
	//
	// The following gRPC error codes can be returned:
	// -  FAILED_PRECONDITION (code 9) if the AVD does not support a
	// configurable
	//
	//	secondary display.
	//
	// -  INVALID_ARGUMENT (code 3) if:
	//   - The same display id is defined multiple times.
	//   - The display configurations are outside valid ranges.
	//     See DisplayConfiguration for details on valid ranges.
	//
	// -  INTERNAL (code 13) if there was an internal emulator failure.
	SetDisplayConfigurations(ctx context.Context, in *DisplayConfigurations, opts ...grpc.CallOption) (*DisplayConfigurations, error)
	// Returns all currently valid logical displays.
	//
	// The gRPC error code FAILED_PRECONDITION (code 9) is returned if the AVD
	// does not support a configurable secondary display.
	GetDisplayConfigurations(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DisplayConfigurations, error)
	// Notifies client of the following changes:
	//
	//   - Virtual scene camera status change.
	//   - Display configuration changes from extended ui. This will only be fired
	//     if the user makes modifications the extended displays through the
	//     extended control tab.
	//
	// Note that this method will send the initial virtual scene state
	// immediately.
	StreamNotification(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notification], error)
	// Rotation angles are relative to the camera's current orientation.
	// The coordinate system is right-handed and is defined as follows:
	//
	//	x axis is pointing right
	//	y axis is pointing up
	//	z axis is pointing towards the viewer
	//
	// The z component of rotation is not used when calling this method.
	RotateVirtualSceneCamera(ctx context.Context, in *RotationRadian, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Velocity is absolute and is measured in meters per second.
	// The coordinate system is right-handed and is defined as follows:
	//
	//	x axis is pointing right
	//	y axis is pointing up
	//	z axis is pointing towards the viewer
	SetVirtualSceneCameraVelocity(ctx context.Context, in *Velocity, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Set foldable posture
	SetPosture(ctx context.Context, in *Posture, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Get the backlight brightness.
	// The following gRPC error codes can be returned:
	// -  FAILED_PRECONDITION (code 9) if the AVD does not support hw-control.
	GetBrightness(ctx context.Context, in *BrightnessValue, opts ...grpc.CallOption) (*BrightnessValue, error)
	// Set the backlight brightness.
	// The following gRPC error codes can be returned:
	// -  FAILED_PRECONDITION (code 9) if the AVD does not support hw-control.
	// -  INVALID_ARGUMENT (code 3) The brightness exceeds the valid range.
	SetBrightness(ctx context.Context, in *BrightnessValue, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Returns the current mode of the primary display of a resizable AVD.
	// The following gRPC error codes can be returned:
	// -  FAILED_PRECONDITION (code 9) if the AVD is not resizable.
	GetDisplayMode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DisplayMode, error)
	// Sets the size of the primary display of a resizable AVD. Fails if the AVD
	// is not resizable. The following gRPC error codes can be returned:
	// -  FAILED_PRECONDITION (code 9) if the AVD is not resizable.
	SetDisplayMode(ctx context.Context, in *DisplayMode, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Changes the XR-related settings. Fails if the AVD is not XR. The
	// following gRPC error codes can be returned:
	// -  FAILED_PRECONDITION (code 9) if the AVD is not XR.
	SetXrOptions(ctx context.Context, in *XrOptions, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Gets the current state of XR-related settings. Fails if the AVD is not
	// XR. The following gRPC error codes can be returned:
	// -  FAILED_PRECONDITION (code 9) if the AVD is not XR.
	GetXrOptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*XrOptions, error)
}

type emulatorControllerClient struct {
	cc grpc.ClientConnInterface
}

func NewEmulatorControllerClient(cc grpc.ClientConnInterface) EmulatorControllerClient {
	return &emulatorControllerClient{cc}
}

func (c *emulatorControllerClient) StreamSensor(ctx context.Context, in *SensorValue, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SensorValue], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmulatorController_ServiceDesc.Streams[0], EmulatorController_StreamSensor_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SensorValue, SensorValue]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamSensorClient = grpc.ServerStreamingClient[SensorValue]

func (c *emulatorControllerClient) GetSensor(ctx context.Context, in *SensorValue, opts ...grpc.CallOption) (*SensorValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensorValue)
	err := c.cc.Invoke(ctx, EmulatorController_GetSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SetSensor(ctx context.Context, in *SensorValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SetSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SetPhysicalModel(ctx context.Context, in *PhysicalModelValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SetPhysicalModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) GetPhysicalModel(ctx context.Context, in *PhysicalModelValue, opts ...grpc.CallOption) (*PhysicalModelValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PhysicalModelValue)
	err := c.cc.Invoke(ctx, EmulatorController_GetPhysicalModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) StreamPhysicalModel(ctx context.Context, in *PhysicalModelValue, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PhysicalModelValue], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmulatorController_ServiceDesc.Streams[1], EmulatorController_StreamPhysicalModel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PhysicalModelValue, PhysicalModelValue]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamPhysicalModelClient = grpc.ServerStreamingClient[PhysicalModelValue]

func (c *emulatorControllerClient) SetClipboard(ctx context.Context, in *ClipData, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SetClipboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) GetClipboard(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ClipData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClipData)
	err := c.cc.Invoke(ctx, EmulatorController_GetClipboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) StreamClipboard(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ClipData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmulatorController_ServiceDesc.Streams[2], EmulatorController_StreamClipboard_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, ClipData]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamClipboardClient = grpc.ServerStreamingClient[ClipData]

func (c *emulatorControllerClient) SetBattery(ctx context.Context, in *BatteryState, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SetBattery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) GetBattery(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*BatteryState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatteryState)
	err := c.cc.Invoke(ctx, EmulatorController_GetBattery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SetGps(ctx context.Context, in *GpsState, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SetGps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) GetGps(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GpsState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GpsState)
	err := c.cc.Invoke(ctx, EmulatorController_GetGps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SendFingerprint(ctx context.Context, in *Fingerprint, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SendFingerprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SendKey(ctx context.Context, in *KeyboardEvent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SendKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SendTouch(ctx context.Context, in *TouchEvent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SendTouch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SendMouse(ctx context.Context, in *MouseEvent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SendMouse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) InjectWheel(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WheelEvent, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmulatorController_ServiceDesc.Streams[3], EmulatorController_InjectWheel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WheelEvent, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_InjectWheelClient = grpc.ClientStreamingClient[WheelEvent, emptypb.Empty]

func (c *emulatorControllerClient) StreamInputEvent(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[InputEvent, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmulatorController_ServiceDesc.Streams[4], EmulatorController_StreamInputEvent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InputEvent, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamInputEventClient = grpc.ClientStreamingClient[InputEvent, emptypb.Empty]

func (c *emulatorControllerClient) SendPhone(ctx context.Context, in *PhoneCall, opts ...grpc.CallOption) (*PhoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PhoneResponse)
	err := c.cc.Invoke(ctx, EmulatorController_SendPhone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SendSms(ctx context.Context, in *SmsMessage, opts ...grpc.CallOption) (*PhoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PhoneResponse)
	err := c.cc.Invoke(ctx, EmulatorController_SendSms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SetPhoneNumber(ctx context.Context, in *PhoneNumber, opts ...grpc.CallOption) (*PhoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PhoneResponse)
	err := c.cc.Invoke(ctx, EmulatorController_SetPhoneNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) GetStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*EmulatorStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmulatorStatus)
	err := c.cc.Invoke(ctx, EmulatorController_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) GetScreenshot(ctx context.Context, in *ImageFormat, opts ...grpc.CallOption) (*Image, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Image)
	err := c.cc.Invoke(ctx, EmulatorController_GetScreenshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) StreamScreenshot(ctx context.Context, in *ImageFormat, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Image], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmulatorController_ServiceDesc.Streams[5], EmulatorController_StreamScreenshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImageFormat, Image]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamScreenshotClient = grpc.ServerStreamingClient[Image]

func (c *emulatorControllerClient) StreamAudio(ctx context.Context, in *AudioFormat, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioPacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmulatorController_ServiceDesc.Streams[6], EmulatorController_StreamAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioFormat, AudioPacket]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamAudioClient = grpc.ServerStreamingClient[AudioPacket]

func (c *emulatorControllerClient) InjectAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AudioPacket, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmulatorController_ServiceDesc.Streams[7], EmulatorController_InjectAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioPacket, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_InjectAudioClient = grpc.ClientStreamingClient[AudioPacket, emptypb.Empty]

// Deprecated: Do not use.
func (c *emulatorControllerClient) GetLogcat(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (*LogMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogMessage)
	err := c.cc.Invoke(ctx, EmulatorController_GetLogcat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) StreamLogcat(ctx context.Context, in *LogMessage, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmulatorController_ServiceDesc.Streams[8], EmulatorController_StreamLogcat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogMessage, LogMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamLogcatClient = grpc.ServerStreamingClient[LogMessage]

func (c *emulatorControllerClient) SetVmState(ctx context.Context, in *VmRunState, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SetVmState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) GetVmState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*VmRunState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VmRunState)
	err := c.cc.Invoke(ctx, EmulatorController_GetVmState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SetDisplayConfigurations(ctx context.Context, in *DisplayConfigurations, opts ...grpc.CallOption) (*DisplayConfigurations, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisplayConfigurations)
	err := c.cc.Invoke(ctx, EmulatorController_SetDisplayConfigurations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) GetDisplayConfigurations(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DisplayConfigurations, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisplayConfigurations)
	err := c.cc.Invoke(ctx, EmulatorController_GetDisplayConfigurations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) StreamNotification(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EmulatorController_ServiceDesc.Streams[9], EmulatorController_StreamNotification_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, Notification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamNotificationClient = grpc.ServerStreamingClient[Notification]

func (c *emulatorControllerClient) RotateVirtualSceneCamera(ctx context.Context, in *RotationRadian, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_RotateVirtualSceneCamera_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SetVirtualSceneCameraVelocity(ctx context.Context, in *Velocity, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SetVirtualSceneCameraVelocity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SetPosture(ctx context.Context, in *Posture, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SetPosture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) GetBrightness(ctx context.Context, in *BrightnessValue, opts ...grpc.CallOption) (*BrightnessValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrightnessValue)
	err := c.cc.Invoke(ctx, EmulatorController_GetBrightness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SetBrightness(ctx context.Context, in *BrightnessValue, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SetBrightness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) GetDisplayMode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DisplayMode, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisplayMode)
	err := c.cc.Invoke(ctx, EmulatorController_GetDisplayMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SetDisplayMode(ctx context.Context, in *DisplayMode, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SetDisplayMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) SetXrOptions(ctx context.Context, in *XrOptions, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, EmulatorController_SetXrOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emulatorControllerClient) GetXrOptions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*XrOptions, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(XrOptions)
	err := c.cc.Invoke(ctx, EmulatorController_GetXrOptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmulatorControllerServer is the server API for EmulatorController service.
// All implementations must embed UnimplementedEmulatorControllerServer
// for forward compatibility.
//
// An EmulatorController service lets you control the emulator.
// Note that this is currently an experimental feature, and that the
// service definition might change without notice. Use at your own risk!
//
// We use the following rough conventions:
//
// streamXXX --> streams values XXX (usually for emulator lifetime). Values
//
//	are updated as soon as they become available.
//
// getXXX    --> gets a single value XXX
// setXXX    --> sets a single value XXX, does not returning state, these
//
//	usually have an observable lasting side effect.
//
// sendXXX   --> send a single event XXX, possibly returning state information.
//
//	android usually responds to these events.
type EmulatorControllerServer interface {
	// set/get/stream the sensor data
	StreamSensor(*SensorValue, grpc.ServerStreamingServer[SensorValue]) error
	GetSensor(context.Context, *SensorValue) (*SensorValue, error)
	SetSensor(context.Context, *SensorValue) (*emptypb.Empty, error)
	// set/get/stream the physical model, this is likely the one you are
	// looking for when you wish to modify the device state.
	SetPhysicalModel(context.Context, *PhysicalModelValue) (*emptypb.Empty, error)
	GetPhysicalModel(context.Context, *PhysicalModelValue) (*PhysicalModelValue, error)
	StreamPhysicalModel(*PhysicalModelValue, grpc.ServerStreamingServer[PhysicalModelValue]) error
	// Atomically set/get the current primary clipboard data.
	// Note that a call to setClipboard will result in an immediate
	// event for those who made a call to streamClipboard and are
	// on a different channel than the one used to set the clipboard.
	SetClipboard(context.Context, *ClipData) (*emptypb.Empty, error)
	GetClipboard(context.Context, *emptypb.Empty) (*ClipData, error)
	// Streams the current data on the clipboard. This will immediately produce
	// a result with the current state of the clipboard after which the stream
	// will block and wait until a new clip event is available from the guest.
	// Calling the setClipboard method above will not result in generating a
	// clip event. It is possible to lose clipboard events if the clipboard
	// updates very rapidly.
	StreamClipboard(*emptypb.Empty, grpc.ServerStreamingServer[ClipData]) error
	// Set/get the battery to the given state.
	SetBattery(context.Context, *BatteryState) (*emptypb.Empty, error)
	GetBattery(context.Context, *emptypb.Empty) (*BatteryState, error)
	// Set the state of the gps.
	// Note: Setting the gps position will not be reflected in the user
	// interface. Keep in mind that android usually only samples the gps at 1
	// hz.
	SetGps(context.Context, *GpsState) (*emptypb.Empty, error)
	// Gets the latest gps state as delivered by the setGps call, or location ui
	// if active.
	//
	// Note: this is not necessarily the actual gps coordinate visible at the
	// time, due to gps sample frequency (usually 1hz).
	GetGps(context.Context, *emptypb.Empty) (*GpsState, error)
	// Simulate a touch event on the finger print sensor.
	SendFingerprint(context.Context, *Fingerprint) (*emptypb.Empty, error)
	// Send a keyboard event. Translating the event.
	SendKey(context.Context, *KeyboardEvent) (*emptypb.Empty, error)
	// Send touch/mouse events. Note that mouse events can be simulated
	// by touch events.
	SendTouch(context.Context, *TouchEvent) (*emptypb.Empty, error)
	SendMouse(context.Context, *MouseEvent) (*emptypb.Empty, error)
	InjectWheel(grpc.ClientStreamingServer[WheelEvent, emptypb.Empty]) error
	// Stream a series of input events to the emulator, the events will
	// arrive in order.
	StreamInputEvent(grpc.ClientStreamingServer[InputEvent, emptypb.Empty]) error
	// Make a phone call.
	SendPhone(context.Context, *PhoneCall) (*PhoneResponse, error)
	// Sends an sms message to the emulator.
	SendSms(context.Context, *SmsMessage) (*PhoneResponse, error)
	// Sends an sms message to the emulator.
	SetPhoneNumber(context.Context, *PhoneNumber) (*PhoneResponse, error)
	// Retrieve the status of the emulator. This will contain general
	// hardware information, and whether the device has booted or not.
	GetStatus(context.Context, *emptypb.Empty) (*EmulatorStatus, error)
	// Gets an individual screenshot in the desired format.
	//
	// The image will be scaled to the desired ImageFormat, while maintaining
	// the aspect ratio. The returned image will never exceed resolution of the
	// device display. Not setting the width or height (i.e. they are 0) will
	// result in using the display width and height.
	//
	// The resulting image will be properly oriented and can be displayed
	// directly without post processing. For example, if the device has a
	// 1080x1920 screen and is in landscape mode and called with no width or
	// height parameter, it will return a 1920x1080 image.
	//
	// The dimensions of the returned image will never exceed the corresponding
	// display dimensions. For example, this method will return a 1920x1080
	// screenshot, if the display resolution is 1080x1920 and a screenshot of
	// 2048x2048 is requested when the device is in landscape mode.
	//
	// This method will return an empty image if the display is not visible.
	GetScreenshot(context.Context, *ImageFormat) (*Image, error)
	// Streams a series of screenshots in the desired format.
	//
	// A new frame will be delivered whenever the device produces a new frame.
	// Beware that this can produce a significant amount of data and that
	// certain translations can be very costly. For example, streaming a series
	// of png images is very cpu intensive.
	//
	// Images are produced according to the getScreenshot API described above.
	//
	// If the display is inactive, or becomes inactive, an empty image will be
	// delivered. Images will be delived again if the display becomes active and
	// new frames are produced.
	StreamScreenshot(*ImageFormat, grpc.ServerStreamingServer[Image]) error
	// Streams a series of audio packets in the desired format.
	// A new frame will be delivered whenever the emulated device
	// produces a new audio frame. You can expect packets to be
	// delivered in intervals of 20-30ms.
	//
	// Be aware that this can block when the emulator does not
	// produce any audio whatsoever!
	StreamAudio(*AudioFormat, grpc.ServerStreamingServer[AudioPacket]) error
	// Injects a series of audio packets to the android microphone.
	// A new frame will be delivered whenever the emulated device
	// requests a new audio frame. Audio is usually delivered at a rate
	// that the emulator is requesting frames. Audio will be stored in a
	// temporary buffer that can hold 300ms of audio.
	//
	// Notes:
	//   - Only the first audio format packet that is delivered will be
	//
	// honored. There is no need to send the audio format multiple times.
	//   - Real time audio currently immediately overrides the buffer. This
	//
	// means you must provide a constant rate of audio packets. The real
	// time mode is experimental. Timestamps of audio packets might be
	// used in the future to improve synchronization.
	//
	// -  INVALID_ARGUMENT (code 3) The sampling rate was too high/low
	// -  INVALID_ARGUMENT (code 3) The audio packet was too large to handle.
	// -  FAILED_PRECONDITION (code 9) If there was a microphone registered
	// already.
	InjectAudio(grpc.ClientStreamingServer[AudioPacket, emptypb.Empty]) error
	// Deprecated: Do not use.
	// Deprecated, please use the streamLogcat method instead.
	GetLogcat(context.Context, *LogMessage) (*LogMessage, error)
	// Streams the logcat output from the emulator.
	// Note that parsed logcat messages are only available after L (Api >23)
	StreamLogcat(*LogMessage, grpc.ServerStreamingServer[LogMessage]) error
	// Transition the virtual machine to the desired state. Note that
	// some states are only observable. For example you cannot transition
	// to the error state.
	SetVmState(context.Context, *VmRunState) (*emptypb.Empty, error)
	// Gets the state of the virtual machine.
	GetVmState(context.Context, *emptypb.Empty) (*VmRunState, error)
	// Atomically changes the current multi-display configuration.
	// After this call the given display configurations will be activated. You
	// can only update secondary displays. Displays with id 0 will be ignored.
	//
	// This call can result in the removal or addition of secondary displays,
	// the final display state can be observed by the returned configuration.
	//
	// The following gRPC error codes can be returned:
	// -  FAILED_PRECONDITION (code 9) if the AVD does not support a
	// configurable
	//
	//	secondary display.
	//
	// -  INVALID_ARGUMENT (code 3) if:
	//   - The same display id is defined multiple times.
	//   - The display configurations are outside valid ranges.
	//     See DisplayConfiguration for details on valid ranges.
	//
	// -  INTERNAL (code 13) if there was an internal emulator failure.
	SetDisplayConfigurations(context.Context, *DisplayConfigurations) (*DisplayConfigurations, error)
	// Returns all currently valid logical displays.
	//
	// The gRPC error code FAILED_PRECONDITION (code 9) is returned if the AVD
	// does not support a configurable secondary display.
	GetDisplayConfigurations(context.Context, *emptypb.Empty) (*DisplayConfigurations, error)
	// Notifies client of the following changes:
	//
	//   - Virtual scene camera status change.
	//   - Display configuration changes from extended ui. This will only be fired
	//     if the user makes modifications the extended displays through the
	//     extended control tab.
	//
	// Note that this method will send the initial virtual scene state
	// immediately.
	StreamNotification(*emptypb.Empty, grpc.ServerStreamingServer[Notification]) error
	// Rotation angles are relative to the camera's current orientation.
	// The coordinate system is right-handed and is defined as follows:
	//
	//	x axis is pointing right
	//	y axis is pointing up
	//	z axis is pointing towards the viewer
	//
	// The z component of rotation is not used when calling this method.
	RotateVirtualSceneCamera(context.Context, *RotationRadian) (*emptypb.Empty, error)
	// Velocity is absolute and is measured in meters per second.
	// The coordinate system is right-handed and is defined as follows:
	//
	//	x axis is pointing right
	//	y axis is pointing up
	//	z axis is pointing towards the viewer
	SetVirtualSceneCameraVelocity(context.Context, *Velocity) (*emptypb.Empty, error)
	// Set foldable posture
	SetPosture(context.Context, *Posture) (*emptypb.Empty, error)
	// Get the backlight brightness.
	// The following gRPC error codes can be returned:
	// -  FAILED_PRECONDITION (code 9) if the AVD does not support hw-control.
	GetBrightness(context.Context, *BrightnessValue) (*BrightnessValue, error)
	// Set the backlight brightness.
	// The following gRPC error codes can be returned:
	// -  FAILED_PRECONDITION (code 9) if the AVD does not support hw-control.
	// -  INVALID_ARGUMENT (code 3) The brightness exceeds the valid range.
	SetBrightness(context.Context, *BrightnessValue) (*emptypb.Empty, error)
	// Returns the current mode of the primary display of a resizable AVD.
	// The following gRPC error codes can be returned:
	// -  FAILED_PRECONDITION (code 9) if the AVD is not resizable.
	GetDisplayMode(context.Context, *emptypb.Empty) (*DisplayMode, error)
	// Sets the size of the primary display of a resizable AVD. Fails if the AVD
	// is not resizable. The following gRPC error codes can be returned:
	// -  FAILED_PRECONDITION (code 9) if the AVD is not resizable.
	SetDisplayMode(context.Context, *DisplayMode) (*emptypb.Empty, error)
	// Changes the XR-related settings. Fails if the AVD is not XR. The
	// following gRPC error codes can be returned:
	// -  FAILED_PRECONDITION (code 9) if the AVD is not XR.
	SetXrOptions(context.Context, *XrOptions) (*emptypb.Empty, error)
	// Gets the current state of XR-related settings. Fails if the AVD is not
	// XR. The following gRPC error codes can be returned:
	// -  FAILED_PRECONDITION (code 9) if the AVD is not XR.
	GetXrOptions(context.Context, *emptypb.Empty) (*XrOptions, error)
	mustEmbedUnimplementedEmulatorControllerServer()
}

// UnimplementedEmulatorControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmulatorControllerServer struct{}

func (UnimplementedEmulatorControllerServer) StreamSensor(*SensorValue, grpc.ServerStreamingServer[SensorValue]) error {
	return status.Error(codes.Unimplemented, "method StreamSensor not implemented")
}
func (UnimplementedEmulatorControllerServer) GetSensor(context.Context, *SensorValue) (*SensorValue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSensor not implemented")
}
func (UnimplementedEmulatorControllerServer) SetSensor(context.Context, *SensorValue) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSensor not implemented")
}
func (UnimplementedEmulatorControllerServer) SetPhysicalModel(context.Context, *PhysicalModelValue) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPhysicalModel not implemented")
}
func (UnimplementedEmulatorControllerServer) GetPhysicalModel(context.Context, *PhysicalModelValue) (*PhysicalModelValue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPhysicalModel not implemented")
}
func (UnimplementedEmulatorControllerServer) StreamPhysicalModel(*PhysicalModelValue, grpc.ServerStreamingServer[PhysicalModelValue]) error {
	return status.Error(codes.Unimplemented, "method StreamPhysicalModel not implemented")
}
func (UnimplementedEmulatorControllerServer) SetClipboard(context.Context, *ClipData) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetClipboard not implemented")
}
func (UnimplementedEmulatorControllerServer) GetClipboard(context.Context, *emptypb.Empty) (*ClipData, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClipboard not implemented")
}
func (UnimplementedEmulatorControllerServer) StreamClipboard(*emptypb.Empty, grpc.ServerStreamingServer[ClipData]) error {
	return status.Error(codes.Unimplemented, "method StreamClipboard not implemented")
}
func (UnimplementedEmulatorControllerServer) SetBattery(context.Context, *BatteryState) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBattery not implemented")
}
func (UnimplementedEmulatorControllerServer) GetBattery(context.Context, *emptypb.Empty) (*BatteryState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBattery not implemented")
}
func (UnimplementedEmulatorControllerServer) SetGps(context.Context, *GpsState) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetGps not implemented")
}
func (UnimplementedEmulatorControllerServer) GetGps(context.Context, *emptypb.Empty) (*GpsState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGps not implemented")
}
func (UnimplementedEmulatorControllerServer) SendFingerprint(context.Context, *Fingerprint) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendFingerprint not implemented")
}
func (UnimplementedEmulatorControllerServer) SendKey(context.Context, *KeyboardEvent) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendKey not implemented")
}
func (UnimplementedEmulatorControllerServer) SendTouch(context.Context, *TouchEvent) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendTouch not implemented")
}
func (UnimplementedEmulatorControllerServer) SendMouse(context.Context, *MouseEvent) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMouse not implemented")
}
func (UnimplementedEmulatorControllerServer) InjectWheel(grpc.ClientStreamingServer[WheelEvent, emptypb.Empty]) error {
	return status.Error(codes.Unimplemented, "method InjectWheel not implemented")
}
func (UnimplementedEmulatorControllerServer) StreamInputEvent(grpc.ClientStreamingServer[InputEvent, emptypb.Empty]) error {
	return status.Error(codes.Unimplemented, "method StreamInputEvent not implemented")
}
func (UnimplementedEmulatorControllerServer) SendPhone(context.Context, *PhoneCall) (*PhoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPhone not implemented")
}
func (UnimplementedEmulatorControllerServer) SendSms(context.Context, *SmsMessage) (*PhoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSms not implemented")
}
func (UnimplementedEmulatorControllerServer) SetPhoneNumber(context.Context, *PhoneNumber) (*PhoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPhoneNumber not implemented")
}
func (UnimplementedEmulatorControllerServer) GetStatus(context.Context, *emptypb.Empty) (*EmulatorStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedEmulatorControllerServer) GetScreenshot(context.Context, *ImageFormat) (*Image, error) {
	return nil, status.Error(codes.Unimplemented, "method GetScreenshot not implemented")
}
func (UnimplementedEmulatorControllerServer) StreamScreenshot(*ImageFormat, grpc.ServerStreamingServer[Image]) error {
	return status.Error(codes.Unimplemented, "method StreamScreenshot not implemented")
}
func (UnimplementedEmulatorControllerServer) StreamAudio(*AudioFormat, grpc.ServerStreamingServer[AudioPacket]) error {
	return status.Error(codes.Unimplemented, "method StreamAudio not implemented")
}
func (UnimplementedEmulatorControllerServer) InjectAudio(grpc.ClientStreamingServer[AudioPacket, emptypb.Empty]) error {
	return status.Error(codes.Unimplemented, "method InjectAudio not implemented")
}
func (UnimplementedEmulatorControllerServer) GetLogcat(context.Context, *LogMessage) (*LogMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLogcat not implemented")
}
func (UnimplementedEmulatorControllerServer) StreamLogcat(*LogMessage, grpc.ServerStreamingServer[LogMessage]) error {
	return status.Error(codes.Unimplemented, "method StreamLogcat not implemented")
}
func (UnimplementedEmulatorControllerServer) SetVmState(context.Context, *VmRunState) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetVmState not implemented")
}
func (UnimplementedEmulatorControllerServer) GetVmState(context.Context, *emptypb.Empty) (*VmRunState, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVmState not implemented")
}
func (UnimplementedEmulatorControllerServer) SetDisplayConfigurations(context.Context, *DisplayConfigurations) (*DisplayConfigurations, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDisplayConfigurations not implemented")
}
func (UnimplementedEmulatorControllerServer) GetDisplayConfigurations(context.Context, *emptypb.Empty) (*DisplayConfigurations, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDisplayConfigurations not implemented")
}
func (UnimplementedEmulatorControllerServer) StreamNotification(*emptypb.Empty, grpc.ServerStreamingServer[Notification]) error {
	return status.Error(codes.Unimplemented, "method StreamNotification not implemented")
}
func (UnimplementedEmulatorControllerServer) RotateVirtualSceneCamera(context.Context, *RotationRadian) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateVirtualSceneCamera not implemented")
}
func (UnimplementedEmulatorControllerServer) SetVirtualSceneCameraVelocity(context.Context, *Velocity) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetVirtualSceneCameraVelocity not implemented")
}
func (UnimplementedEmulatorControllerServer) SetPosture(context.Context, *Posture) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPosture not implemented")
}
func (UnimplementedEmulatorControllerServer) GetBrightness(context.Context, *BrightnessValue) (*BrightnessValue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBrightness not implemented")
}
func (UnimplementedEmulatorControllerServer) SetBrightness(context.Context, *BrightnessValue) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBrightness not implemented")
}
func (UnimplementedEmulatorControllerServer) GetDisplayMode(context.Context, *emptypb.Empty) (*DisplayMode, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDisplayMode not implemented")
}
func (UnimplementedEmulatorControllerServer) SetDisplayMode(context.Context, *DisplayMode) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDisplayMode not implemented")
}
func (UnimplementedEmulatorControllerServer) SetXrOptions(context.Context, *XrOptions) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetXrOptions not implemented")
}
func (UnimplementedEmulatorControllerServer) GetXrOptions(context.Context, *emptypb.Empty) (*XrOptions, error) {
	return nil, status.Error(codes.Unimplemented, "method GetXrOptions not implemented")
}
func (UnimplementedEmulatorControllerServer) mustEmbedUnimplementedEmulatorControllerServer() {}
func (UnimplementedEmulatorControllerServer) testEmbeddedByValue()                            {}

// UnsafeEmulatorControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmulatorControllerServer will
// result in compilation errors.
type UnsafeEmulatorControllerServer interface {
	mustEmbedUnimplementedEmulatorControllerServer()
}

func RegisterEmulatorControllerServer(s grpc.ServiceRegistrar, srv EmulatorControllerServer) {
	// If the following call panics, it indicates UnimplementedEmulatorControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmulatorController_ServiceDesc, srv)
}

func _EmulatorController_StreamSensor_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SensorValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmulatorControllerServer).StreamSensor(m, &grpc.GenericServerStream[SensorValue, SensorValue]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamSensorServer = grpc.ServerStreamingServer[SensorValue]

func _EmulatorController_GetSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetSensor(ctx, req.(*SensorValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SetSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SetSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SetSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SetSensor(ctx, req.(*SensorValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SetPhysicalModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhysicalModelValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SetPhysicalModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SetPhysicalModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SetPhysicalModel(ctx, req.(*PhysicalModelValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_GetPhysicalModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhysicalModelValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetPhysicalModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetPhysicalModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetPhysicalModel(ctx, req.(*PhysicalModelValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_StreamPhysicalModel_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PhysicalModelValue)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmulatorControllerServer).StreamPhysicalModel(m, &grpc.GenericServerStream[PhysicalModelValue, PhysicalModelValue]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamPhysicalModelServer = grpc.ServerStreamingServer[PhysicalModelValue]

func _EmulatorController_SetClipboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClipData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SetClipboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SetClipboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SetClipboard(ctx, req.(*ClipData))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_GetClipboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetClipboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetClipboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetClipboard(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_StreamClipboard_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmulatorControllerServer).StreamClipboard(m, &grpc.GenericServerStream[emptypb.Empty, ClipData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamClipboardServer = grpc.ServerStreamingServer[ClipData]

func _EmulatorController_SetBattery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatteryState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SetBattery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SetBattery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SetBattery(ctx, req.(*BatteryState))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_GetBattery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetBattery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetBattery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetBattery(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SetGps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GpsState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SetGps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SetGps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SetGps(ctx, req.(*GpsState))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_GetGps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetGps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetGps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetGps(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SendFingerprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Fingerprint)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SendFingerprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SendFingerprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SendFingerprint(ctx, req.(*Fingerprint))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SendKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyboardEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SendKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SendKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SendKey(ctx, req.(*KeyboardEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SendTouch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TouchEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SendTouch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SendTouch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SendTouch(ctx, req.(*TouchEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SendMouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MouseEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SendMouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SendMouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SendMouse(ctx, req.(*MouseEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_InjectWheel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmulatorControllerServer).InjectWheel(&grpc.GenericServerStream[WheelEvent, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_InjectWheelServer = grpc.ClientStreamingServer[WheelEvent, emptypb.Empty]

func _EmulatorController_StreamInputEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmulatorControllerServer).StreamInputEvent(&grpc.GenericServerStream[InputEvent, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamInputEventServer = grpc.ClientStreamingServer[InputEvent, emptypb.Empty]

func _EmulatorController_SendPhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhoneCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SendPhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SendPhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SendPhone(ctx, req.(*PhoneCall))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SendSms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SendSms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SendSms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SendSms(ctx, req.(*SmsMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SetPhoneNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PhoneNumber)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SetPhoneNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SetPhoneNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SetPhoneNumber(ctx, req.(*PhoneNumber))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_GetScreenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageFormat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetScreenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetScreenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetScreenshot(ctx, req.(*ImageFormat))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_StreamScreenshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ImageFormat)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmulatorControllerServer).StreamScreenshot(m, &grpc.GenericServerStream[ImageFormat, Image]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamScreenshotServer = grpc.ServerStreamingServer[Image]

func _EmulatorController_StreamAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AudioFormat)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmulatorControllerServer).StreamAudio(m, &grpc.GenericServerStream[AudioFormat, AudioPacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamAudioServer = grpc.ServerStreamingServer[AudioPacket]

func _EmulatorController_InjectAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmulatorControllerServer).InjectAudio(&grpc.GenericServerStream[AudioPacket, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_InjectAudioServer = grpc.ClientStreamingServer[AudioPacket, emptypb.Empty]

func _EmulatorController_GetLogcat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetLogcat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetLogcat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetLogcat(ctx, req.(*LogMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_StreamLogcat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmulatorControllerServer).StreamLogcat(m, &grpc.GenericServerStream[LogMessage, LogMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamLogcatServer = grpc.ServerStreamingServer[LogMessage]

func _EmulatorController_SetVmState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VmRunState)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SetVmState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SetVmState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SetVmState(ctx, req.(*VmRunState))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_GetVmState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetVmState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetVmState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetVmState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SetDisplayConfigurations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisplayConfigurations)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SetDisplayConfigurations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SetDisplayConfigurations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SetDisplayConfigurations(ctx, req.(*DisplayConfigurations))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_GetDisplayConfigurations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetDisplayConfigurations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetDisplayConfigurations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetDisplayConfigurations(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_StreamNotification_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmulatorControllerServer).StreamNotification(m, &grpc.GenericServerStream[emptypb.Empty, Notification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EmulatorController_StreamNotificationServer = grpc.ServerStreamingServer[Notification]

func _EmulatorController_RotateVirtualSceneCamera_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotationRadian)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).RotateVirtualSceneCamera(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_RotateVirtualSceneCamera_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).RotateVirtualSceneCamera(ctx, req.(*RotationRadian))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SetVirtualSceneCameraVelocity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Velocity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SetVirtualSceneCameraVelocity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SetVirtualSceneCameraVelocity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SetVirtualSceneCameraVelocity(ctx, req.(*Velocity))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SetPosture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Posture)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SetPosture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SetPosture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SetPosture(ctx, req.(*Posture))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_GetBrightness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrightnessValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetBrightness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetBrightness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetBrightness(ctx, req.(*BrightnessValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SetBrightness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrightnessValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SetBrightness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SetBrightness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SetBrightness(ctx, req.(*BrightnessValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_GetDisplayMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetDisplayMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetDisplayMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetDisplayMode(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SetDisplayMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisplayMode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SetDisplayMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SetDisplayMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SetDisplayMode(ctx, req.(*DisplayMode))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_SetXrOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XrOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).SetXrOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_SetXrOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).SetXrOptions(ctx, req.(*XrOptions))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmulatorController_GetXrOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmulatorControllerServer).GetXrOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmulatorController_GetXrOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmulatorControllerServer).GetXrOptions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// EmulatorController_ServiceDesc is the grpc.ServiceDesc for EmulatorController service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmulatorController_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "android.emulation.control.EmulatorController",
	HandlerType: (*EmulatorControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getSensor",
			Handler:    _EmulatorController_GetSensor_Handler,
		},
		{
			MethodName: "setSensor",
			Handler:    _EmulatorController_SetSensor_Handler,
		},
		{
			MethodName: "setPhysicalModel",
			Handler:    _EmulatorController_SetPhysicalModel_Handler,
		},
		{
			MethodName: "getPhysicalModel",
			Handler:    _EmulatorController_GetPhysicalModel_Handler,
		},
		{
			MethodName: "setClipboard",
			Handler:    _EmulatorController_SetClipboard_Handler,
		},
		{
			MethodName: "getClipboard",
			Handler:    _EmulatorController_GetClipboard_Handler,
		},
		{
			MethodName: "setBattery",
			Handler:    _EmulatorController_SetBattery_Handler,
		},
		{
			MethodName: "getBattery",
			Handler:    _EmulatorController_GetBattery_Handler,
		},
		{
			MethodName: "setGps",
			Handler:    _EmulatorController_SetGps_Handler,
		},
		{
			MethodName: "getGps",
			Handler:    _EmulatorController_GetGps_Handler,
		},
		{
			MethodName: "sendFingerprint",
			Handler:    _EmulatorController_SendFingerprint_Handler,
		},
		{
			MethodName: "sendKey",
			Handler:    _EmulatorController_SendKey_Handler,
		},
		{
			MethodName: "sendTouch",
			Handler:    _EmulatorController_SendTouch_Handler,
		},
		{
			MethodName: "sendMouse",
			Handler:    _EmulatorController_SendMouse_Handler,
		},
		{
			MethodName: "sendPhone",
			Handler:    _EmulatorController_SendPhone_Handler,
		},
		{
			MethodName: "sendSms",
			Handler:    _EmulatorController_SendSms_Handler,
		},
		{
			MethodName: "setPhoneNumber",
			Handler:    _EmulatorController_SetPhoneNumber_Handler,
		},
		{
			MethodName: "getStatus",
			Handler:    _EmulatorController_GetStatus_Handler,
		},
		{
			MethodName: "getScreenshot",
			Handler:    _EmulatorController_GetScreenshot_Handler,
		},
		{
			MethodName: "getLogcat",
			Handler:    _EmulatorController_GetLogcat_Handler,
		},
		{
			MethodName: "setVmState",
			Handler:    _EmulatorController_SetVmState_Handler,
		},
		{
			MethodName: "getVmState",
			Handler:    _EmulatorController_GetVmState_Handler,
		},
		{
			MethodName: "setDisplayConfigurations",
			Handler:    _EmulatorController_SetDisplayConfigurations_Handler,
		},
		{
			MethodName: "getDisplayConfigurations",
			Handler:    _EmulatorController_GetDisplayConfigurations_Handler,
		},
		{
			MethodName: "rotateVirtualSceneCamera",
			Handler:    _EmulatorController_RotateVirtualSceneCamera_Handler,
		},
		{
			MethodName: "setVirtualSceneCameraVelocity",
			Handler:    _EmulatorController_SetVirtualSceneCameraVelocity_Handler,
		},
		{
			MethodName: "setPosture",
			Handler:    _EmulatorController_SetPosture_Handler,
		},
		{
			MethodName: "getBrightness",
			Handler:    _EmulatorController_GetBrightness_Handler,
		},
		{
			MethodName: "setBrightness",
			Handler:    _EmulatorController_SetBrightness_Handler,
		},
		{
			MethodName: "getDisplayMode",
			Handler:    _EmulatorController_GetDisplayMode_Handler,
		},
		{
			MethodName: "setDisplayMode",
			Handler:    _EmulatorController_SetDisplayMode_Handler,
		},
		{
			MethodName: "setXrOptions",
			Handler:    _EmulatorController_SetXrOptions_Handler,
		},
		{
			MethodName: "getXrOptions",
			Handler:    _EmulatorController_GetXrOptions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "streamSensor",
			Handler:       _EmulatorController_StreamSensor_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "streamPhysicalModel",
			Handler:       _EmulatorController_StreamPhysicalModel_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "streamClipboard",
			Handler:       _EmulatorController_StreamClipboard_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "injectWheel",
			Handler:       _EmulatorController_InjectWheel_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "streamInputEvent",
			Handler:       _EmulatorController_StreamInputEvent_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "streamScreenshot",
			Handler:       _EmulatorController_StreamScreenshot_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "streamAudio",
			Handler:       _EmulatorController_StreamAudio_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "injectAudio",
			Handler:       _EmulatorController_InjectAudio_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "streamLogcat",
			Handler:       _EmulatorController_StreamLogcat_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "streamNotification",
			Handler:       _EmulatorController_StreamNotification_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "emulator_controller.proto",
}
